Repository zio/zio-http, pull requests merged in 2021-04, with the labels that each got.

#108 fix(build): add sonatypeCredentialHost on global context
  build.sbt
Labels: automerge, bug, skip-changelog

#110 doc(readme): add snapshot badge
  README.md
Labels: chore, skip-changelog

#111 Chore(*): add tags support for github-actions
  .github/workflows/ci.yml
  build.sbt
Labels: skip-changelog

#112 chore(*): sonatypeRepository
  build.sbt
Labels: skip-changelog

#113 Update netty-all to 4.1.63.Final
  build.sbt
Labels: skip-changelog

#115 Chore: Workflow Cleanup
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
  build.sbt
Labels: automerge, chore

#119 Update sbt to 1.5.0
  project/build.properties
Labels: automerge, skip-changelog

#116 Add http-header utilities
  zio-http/src/main/scala/zhttp/http/Header.scala
Labels: automerge, enhancement

#117 Add more http statuses
  zio-http/src/main/scala/zhttp/http/Status.scala
Labels: automerge, enhancement

#122 Build: Update build.sbt
  build.sbt
  project/BuildHelper.scala
Labels: automerge, chore

#125 Update sbt-scala3-migrate to 0.3.3
  project/plugins.sbt
Labels: automerge, chore

#124 feat(http): add socket server implementation
  zio-http/src/main/scala/zhttp/http/SocketServer.scala
Labels: automerge, skip-changelog

#126 Add Http Errors + Update default messages error messages
  zio-http/src/main/scala/zhttp/http/HttpError.scala
Labels: enhancement

#127 Remove sbt-dotty plugin
  build.sbt
  project/BuildHelper.scala
  project/plugins.sbt
Labels: automerge, chore

#129 refactor(Response): SocketResponse fix error variance issue in scala 3
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: automerge

#123 Feature: Socket API Redesign
  .scalafmt.conf
  example/src/main/scala/HelloWorldAdvanced.scala
  example/src/main/scala/WebSocketAdvanced.scala
  example/src/main/scala/WebSocketEcho.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpNestedFlatMapEval.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/ResponseOps.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala
  zio-http/src/main/scala/zhttp/service/DecodeJResponse.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/main/scala/zhttp/service/EncodeResponse.scala
  zio-http/src/main/scala/zhttp/service/HttpMessageCodec.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/UnsafeChannelExecutor.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketError.scala
  zio-http/src/main/scala/zhttp/socket/package.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
Labels: automerge, enhancement

#134 Fix builds not getting triggered via automerge
  .github/workflows/auto-merge.yml
Labels: chore

#138 refactor(Socket): Change default value
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketConfig.scala
Labels: automerge, skip-changelog

#135 Feature: Extend WebSocket Configuration
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/socket/CloseStatus.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketConfig.scala
Labels: automerge, enhancement

#141 Update sbt-updates to 0.5.3
  project/plugins.sbt
Labels: automerge, chore

#140 refactor(Socket): make protocol configs optional
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/socket/SocketConfig.scala
Labels: automerge, performance

#145 Rename socket's compose operator
  example/src/main/scala/WebSocketAdvanced.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
Labels: automerge, enhancement

#149 Update ZIO version
  .github/workflows/ci.yml
  build.sbt
  project/BuildHelper.scala
Labels: automerge, chore

#144 Extend support for various content encodings
  example/src/main/scala/SimpleClient.scala
  zio-http/src/main/scala/zhttp/http/HttpContent.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/ResponseOps.scala
  zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala
  zio-http/src/main/scala/zhttp/service/DecodeJResponse.scala
  zio-http/src/main/scala/zhttp/service/EncodeResponse.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
Labels: automerge, enhancement

#151 Example: Update advanced example
  example/src/main/scala/HelloWorldAdvanced.scala
Labels: automerge, enhancement

#143 Streaming Response
  README.md
  example/src/main/scala/SimpleClient.scala
  example/src/main/scala/StreamingResponse.scala
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/http/HttpContent.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/ResponseOps.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala
  zio-http/src/main/scala/zhttp/service/DecodeJResponse.scala
  zio-http/src/main/scala/zhttp/service/EncodeResponse.scala
  zio-http/src/main/scala/zhttp/service/UnsafeChannelExecutor.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
Labels: automerge, docs, enhancement

#152 Add file streaming example
  README.md
  example/src/main/scala/FileStreaming.scala
  example/src/main/scala/StreamingResponse.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
Labels: automerge, docs, enhancement

#154 Fix netty exception: java.lang.IllegalStateException: unexpected message type: DefaultHttpResponse, state: 1
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
Labels: automerge, bug

#155 Refactor `HttpData.fromByteBuf` to use `ByteBuf.Utils`
  zio-http/src/main/scala/zhttp/http/HttpData.scala
Labels: automerge, refactor

#157 Extend expressivity of web socket API
  example/src/main/scala/WebSocketAdvanced.scala
  example/src/main/scala/WebSocketEcho.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/ResponseOps.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/socket/Conversion.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/main/scala/zhttp/socket/SocketConfig.scala
  zio-http/src/main/scala/zhttp/socket/SocketDecoder.scala
  zio-http/src/main/scala/zhttp/socket/SocketProtocol.scala
  zio-http/src/main/scala/zhttp/socket/package.scala
Labels: automerge, enhancement

#159 Chore: Update scala 3 version with zio 1.0.7 version
  .github/workflows/ci.yml
  build.sbt
  project/BuildHelper.scala
Labels: automerge, chore

#162 Update sbt to 1.5.1
  project/build.properties
Labels: automerge

#158 Extend Http API
  example/src/main/scala/FileStreaming.scala
  example/src/main/scala/HelloWorld.scala
  example/src/main/scala/HelloWorldAdvanced.scala
  example/src/main/scala/StreamingResponse.scala
  example/src/main/scala/WebSocketAdvanced.scala
  example/src/main/scala/WebSocketEcho.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpConcatEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpNestedFlatMapEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpRouteTextPerf.scala
  zio-http/src/main/scala/zhttp/http/CanConcatenate.scala
  zio-http/src/main/scala/zhttp/http/CanSupportPartial.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpApp.scala
  zio-http/src/main/scala/zhttp/http/HttpChannel.scala
  zio-http/src/main/scala/zhttp/http/HttpConstructors.scala
  zio-http/src/main/scala/zhttp/http/HttpExecutors.scala
  zio-http/src/main/scala/zhttp/http/HttpResult.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/UnsafeChannelExecutor.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/test/scala/zhttp/http/HttpChannelSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpResultSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientContentLengthSpec.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: automerge, enhancement

#164 Update ClientSpec
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
Labels: automerge, chore

#156 Add query string parsing
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
Labels: automerge, enhancement

#166 Add `Collect` constructor in Http
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpCollectEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpCombineEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpConcatEval.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpResult.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: automerge, performance

#133 Header helpers to extract common headers values
  zio-http/src/main/scala/zhttp/http/HasHeaders.scala
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/http/HeadersHelpers.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: automerge, enhancement

#171 Update sbt-scala3-migrate to 0.4.0
  project/plugins.sbt
Labels: automerge
