Repository zio/zio-http, pull requests merged in 2021-07, with the labels that each got.

#285 Fix: allow multiple headers same type
  zio-http/src/main/scala/zhttp/service/EncodeResponse.scala
  zio-http/src/test/scala/zhttp/service/EncodeResponseSpec.scala
Labels: automerge, bug

#289 Update README.md
  README.md
Labels: automerge, docs

#264 feat: Add optional remoteAddress to Request
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
Labels: enhancement

#290 Update scala-collection-compat to 2.5.0
  build.sbt
Labels: chore

#297 constructor for FromStream
  zio-http/src/main/scala/zhttp/socket/Socket.scala
Labels: automerge, bug

#296 test(ClientHttpsSpec): marked test as flaky
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
Labels: automerge, bug, chore

#301 Feature: Http Enhancements
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpResult.scala
  zio-http/src/main/scala/zhttp/http/package.scala
Labels: enhancement

#302 Performance: URL builder performance
  zio-http/src/main/scala/zhttp/http/URL.scala
Labels: performance

#305 Add helpers for redirect methods.
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/http/ResponseHelpers.scala
  zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala
Labels: automerge, enhancement

#309 Add documentation for requests
  docs/index.md
Labels: documentation

#314 fix(SSLSpec): added timeout and flaky in test
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
Labels: automerge, bug

#315 Update jwt-core to 8.0.3
  build.sbt
Labels: chore

#308 Add basic request testing util
  .github/workflows/ci.yml
  README.md
  build.sbt
  docs/index.md
  project/BuildHelper.scala
  zio-http-test/src/main/scala/zhttp/test/test.scala
Labels: enhancement
