Repository zio/zio-http, pull requests merged in 2021-11, with the labels that each got.

#452 Rewrite CORS to use new middleware API
  example/src/main/scala/HelloWorldWithCORS.scala
  zio-http/src/main/scala/zhttp/http/CORS.scala
  zio-http/src/main/scala/zhttp/http/middleware/HttpMiddleware.scala
  zio-http/src/test/scala/zhttp/service/CORSSpec.scala
Labels: zio-hackathon

#481 Fix: https server example
  example/src/main/resources/keystore.jks
  example/src/main/resources/localhost.cert
  example/src/main/resources/mysslstore.jks
  example/src/main/scala/HttpsHelloWorld.scala
Labels: bug, automerge

#469 Update netty-all to 4.1.70.Final
  project/Dependencies.scala
Labels: automerge

#478 Update scala-collection-compat to 2.6.0
  project/Dependencies.scala
Labels: automerge

#466 Update sbt-bloop to 1.4.11
  project/plugins.sbt
Labels: automerge

#472 Update netty-incubator-transport-native-io_uring to 0.0.10.Final
  project/Dependencies.scala
Labels: automerge

#485 Feat: ifThenElse method in HttpMiddleware
  zio-http/src/main/scala/zhttp/http/middleware/HttpMiddleware.scala
  zio-http/src/test/scala/zhttp/internal/HttpAppTestExtensions.scala
  zio-http/src/test/scala/zhttp/middleware/HttpMiddlewareSpec.scala
Labels: automerge

#459 fix(cookie): multipleDecode method in cookie
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/HasCookie.scala
  zio-http/src/main/scala/zhttp/http/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/test/scala/zhttp/experiment/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: automerge

#487 Scoverage with Codecov
  .github/workflows/ci.yml
  build.sbt
  project/WorkflowHelper.scala
Labels: chore, zio-hackathon

#506 Feat: authentication middleware
  example/src/main/scala/example/BasicAuth.scala
  example/src/main/scala/example/HelloWorldTwirl.scala
  zio-http/src/main/scala/zhttp/http/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/middleware/HttpMiddleware.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/experiment/internal/HttpMessageAssertions.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpAppTestExtensions.scala
  zio-http/src/test/scala/zhttp/middleware/HttpMiddlewareSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientContentLengthSpec.scala
Labels: enhancement, automerge

#489 Feature: Http 100 continue
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
Labels: enhancement, automerge

#534 Scoverage Percentage Brought Down
  .github/workflows/ci.yml
  build.sbt
Labels: automerge, chore

#520 Update sbt-scalafix to 0.9.32
  project/plugins.sbt
Labels: automerge, chore

#463 Update scala-library to 2.13.7
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: automerge, chore

#521 Update scalafmt-core to 3.1.1
  .scalafmt.conf
Labels: automerge, chore

#539 Update sbt-scalafmt to 2.4.4
  project/plugins.sbt
Labels: automerge, chore

#547 Update scalafmt-core to 3.1.2
  .scalafmt.conf
Labels: automerge

#563 For Main | Path file refactored
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
Labels: automerge

#564 For Main | added url from release/next
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
Labels: automerge
