Repository zio/zio-http, pull requests merged in 2021-03, with the labels that each got.

#11 doc(benchmarks): add finagle benchmark result
  BENCHMARKS.md
Labels: automerge

#13 Fix: Connection Closed Exception
  zio-http/src/main/scala/zhttp/service/server/ServerHttpExceptionHandler.scala
Labels: automerge

#23 doc(benchmark): url correction
  BENCHMARKS.md
Labels: automerge

#37 fix(domain): add default headers in Response
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: automerge

#39 chore(build): crossVersion publishing
  README.md
  build.sbt
Labels: automerge

#41 fix(Response): add content-type Header
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: automerge

#60 Refactor: Enhance Server API
  README.md
  example/src/main/scala/HelloWorld.scala
  example/src/main/scala/HelloWorldAdvanced.scala
  example/src/main/scala/SocketEchoServer.scala
  zio-http/src/main/scala/zhttp/http/CanConcatenate.scala
  zio-http/src/main/scala/zhttp/http/CanSupportPartial.scala
  zio-http/src/main/scala/zhttp/http/HttpConstructors.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/LeakDetectionLevel.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
Labels: automerge

#69 Update sbt to 1.4.9
  project/build.properties
Labels: automerge

#65 Update sbt-updates to 0.5.2
  project/plugins.sbt
Labels: automerge

#66 Update zio, zio-streams, zio-test, ... to 1.0.5
  build.sbt
Labels: automerge

#80 refactor(Http): Decode Should throw a Http error instead of throwable
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/service/HttpMessageCodec.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
Labels: automerge

#90 Update sbt-scala3-migrate to 0.3.2
  project/plugins.sbt
Labels: automerge

#82 chore(*): Automate releases vi CI
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: automerge, chore

#87 added content-length header for nonempty content
  zio-http/src/main/scala/zhttp/service/HttpMessageCodec.scala
  zio-http/src/test/scala/zhttp/service/ClientContentLengthSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: automerge, enhancement

#98 automated release fix
  build.sbt
Labels: bug, skip-changelog
