Repository zio/zio-http, pull requests merged in 2021-05, with the labels that each got.

#172 doc: update website
  docs/index.md
Labels: automerge, docs

#169 Fix HttpResult compositional semantics
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpResult.scala
  zio-http/src/main/scala/zhttp/service/UnsafeChannelExecutor.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/test/scala/zhttp/http/HttpResultAssertion.scala
  zio-http/src/test/scala/zhttp/http/HttpResultSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: bug

#175 Example: Add authentication middleware example
  README.md
  build.sbt
  docs/index.md
  example/src/main/scala/Authentication.scala
  zio-http/src/main/scala/zhttp/http/HttpApp.scala
  zio-http/src/main/scala/zhttp/http/package.scala
Labels: docs

#181 feat: Add Http.route
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: automerge, enhancement

#183 Fix: collectM unable to create more than 1 socket connection
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
Labels: bug

#174 Authorization header helpers
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/http/HeadersHelpers.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: enhancement

#190 Support Scala 2.12
  .github/workflows/ci.yml
  build.sbt
  example/src/main/scala/HelloWorld.scala
  example/src/main/scala/HelloWorldAdvanced.scala
  example/src/main/scala/HelloWorldWithCORS.scala
  example/src/main/scala/StreamingResponse.scala
  project/BuildHelper.scala
  project/ScalaSettings.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpCollectEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpCombineEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpNestedFlatMapEval.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/service/ChannelFuture.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/UnsafeChannelExecutor.scala
  zio-http/src/test/scala/zhttp/service/CORSSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientContentLengthSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: automerge, chore

#192 Update sbt-scala3-migrate to 0.4.1
  project/plugins.sbt
Labels: chore

#205 fix(server): close the connection on failure without cause
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
Labels: automerge, bug

#210 Update sbt-scala3-migrate to 0.4.2
  project/plugins.sbt
Labels: automerge, chore

#214 Add commas to benchmarks for readability ;)
  README.md
Labels: automerge, chore

#215 Upgrade Scala 3 to final release
  .github/workflows/ci.yml
  build.sbt
  example/src/main/scala/WebSocketAdvanced.scala
  project/BuildHelper.scala
Labels: chore

#197 feat: http error handler
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/server/ServerHttpExceptionHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
Labels: automerge, enhancement

#221 refactor(request): change structure of Request
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala
  zio-http/src/test/scala/zhttp/service/ClientContentLengthSpec.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
Labels: automerge, enhancement

#220 Update netty-all to 4.1.65.Final
  build.sbt
Labels: automerge, chore

#222 Added Example for concrete entity
  example/src/main/scala/ConcreteEntity.scala
  zio-http/src/main/scala/zhttp/http/ResponseHelpers.scala
Labels: automerge

#225 Update scala-library to 2.13.6
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: chore

#226 Fix(example): added comments in concrete entity example
  example/src/main/scala/ConcreteEntity.scala
Labels: documentation
