Repository zio/zio-http, pull requests merged in 2021-08, with the labels that each got.

#316 refactor: remove AliasModule
  example/src/main/scala/FileStreaming.scala
  zio-http/src/main/scala/zhttp/core/AliasModule.scala
  zio-http/src/main/scala/zhttp/core/ByteBuf.scala
  zio-http/src/main/scala/zhttp/core/package.scala
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/http/HeadersHelpers.scala
  zio-http/src/main/scala/zhttp/http/Method.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Scheme.scala
  zio-http/src/main/scala/zhttp/http/Status.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/service/ChannelFactory.scala
  zio-http/src/main/scala/zhttp/service/ChannelFuture.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala
  zio-http/src/main/scala/zhttp/service/DecodeJResponse.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/main/scala/zhttp/service/EncodeResponse.scala
  zio-http/src/main/scala/zhttp/service/EventLoopGroup.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/UnsafeChannelExecutor.scala
  zio-http/src/main/scala/zhttp/service/client/ClientChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/client/ClientHttpChannelReader.scala
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zhttp/service/client/ClientSSLHandler.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/HttpOnHttpsHandler.scala
  zio-http/src/main/scala/zhttp/service/server/LeakDetectionLevel.scala
  zio-http/src/main/scala/zhttp/service/server/OptionalSSLHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelFactory.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSSLHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/socket/CloseStatus.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/main/scala/zhttp/socket/SocketDecoder.scala
  zio-http/src/main/scala/zhttp/socket/SocketProtocol.scala
  zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/EncodeResponseSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
Labels: automerge, enhancement

#320 docs: fix examples
  docs/index.md
Labels: documentation

#323 Fix: Route matching with encoded paths
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug, automerge

#327 added helper for text/html and text/yaml
  zio-http/src/main/scala/zhttp/http/Header.scala
Labels: enhancement

#335 Fix link to WebSocket Server
  README.md
Labels: documentation

#329 feat(server): add start overloads
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: enhancement, automerge

#287 feat(charset): charset handling in request
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
Labels: enhancement, automerge

#337 Make path extraction right associative
  example/src/main/scala/Authentication.scala
  example/src/main/scala/FileStreaming.scala
  example/src/main/scala/HelloWorld.scala
  example/src/main/scala/HelloWorldAdvanced.scala
  example/src/main/scala/HelloWorldWithCORS.scala
  example/src/main/scala/HttpsHelloWorld.scala
  example/src/main/scala/StickyThread.scala
  example/src/main/scala/StreamingResponse.scala
  example/src/main/scala/WebSocketAdvanced.scala
  example/src/main/scala/WebSocketEcho.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpRouteTextPerf.scala
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/main/scala/zhttp/http/RouteDecoderModule.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
  zio-http/src/test/scala/zhttp/service/CORSSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientContentLengthSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement
