Repository zio/zio-http, pull requests merged in 2021-06, with the labels that each got.

#234 Feature: Enhance operators for client request.
  example/src/main/scala/SimpleClient.scala
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
Labels: automerge, bug, enhancement

#196 Fix: CORS middleware to handle OPTIONS requests completely on its own
  zio-http/src/main/scala/zhttp/http/CORS.scala
  zio-http/src/test/scala/zhttp/service/CORSSpec.scala
Labels: bug

#253 Update jwt-core to 8.0.2
  build.sbt
Labels: chore

#254 Refactor: Wrap HttpApp around Http
  example/src/main/scala/Authentication.scala
  example/src/main/scala/ConcreteEntity.scala
  zio-http/src/main/scala/zhttp/http/CORS.scala
  zio-http/src/main/scala/zhttp/http/HttpApp.scala
  zio-http/src/main/scala/zhttp/http/package.scala
Labels: automerge, enhancement

#266 feat: Use implicit class for HttpApp syntax
  example/src/main/scala/Authentication.scala
  example/src/main/scala/ConcreteEntity.scala
  zio-http/src/main/scala/zhttp/http/CORS.scala
  zio-http/src/main/scala/zhttp/http/HttpApp.scala
  zio-http/src/main/scala/zhttp/http/HttpAppSyntax.scala
  zio-http/src/main/scala/zhttp/http/package.scala
Labels: automerge, refactor

#256 SSL: Server & Client
  example/src/main/resources/keystore.jks
  example/src/main/resources/truststore.jks
  example/src/main/scala/HttpsClient.scala
  example/src/main/scala/HttpsHelloWorld.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/client/ClientChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/client/ClientSSLHandler.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/HttpOnHttpsHandler.scala
  zio-http/src/main/scala/zhttp/service/server/OptionalSSLHandler.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSSLHandler.scala
  zio-http/src/test/resources/truststore.jks
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
Labels: automerge, enhancement

#268 Fix: Query parameters being ignored in client requests
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/test/scala/zhttp/http/EncodeRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
Labels: automerge, bug

#271 fix(Header): basic auth header fixed
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: automerge, bug

#278 fix(ClientHttpsSpec): fixed https client tests
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
Labels: automerge, refactor
