Repository zio/zio-http, pull requests merged in 2021-10, with the labels that each got.

#375 Refactor: And type param to ContentDecoder for input type
  zio-http/src/main/scala/zhttp/experiment/ContentDecoder.scala
  zio-http/src/main/scala/zhttp/http/HttpApp.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/test/scala/zhttp/experiment/internal/HttpMessageAssertions.scala
Labels: enhancement

#433 Websocket
  zio-http/src/main/scala/zhttp/http/HeadersHelpers.scala
  zio-http/src/main/scala/zhttp/http/HttpAttribute.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: enhancement, blocker

#439 Update jwt-core to 9.0.2
  project/Dependencies.scala
Labels: automerge, chore

#440 Update scalafmt-core to 3.0.8
  .scalafmt.conf
  build.sbt
  example/src/main/scala/ConcreteEntity.scala
  example/src/main/scala/HttpsClient.scala
  project/ScalaSettings.scala
Labels: automerge, chore

#444 Example of middleware usage
  example/src/main/scala/HelloWorldWithMiddlewares.scala
Labels: documentation, zio-hackathon
