Repository zio/zio-http, pull requests merged in 2021-12, with the labels that each got.

#596 Scaladoc Doc generation failing
  zio-http/src/main/scala/zhttp/http/RouteDecoderModule.scala
Labels: automerge

#597 fix: AuthMiddleware
  zio-http/src/main/scala/zhttp/http/Middleware.scala
Labels: documentation, automerge

#599 Refactor(Examples): removed sticky thread example
  example/src/main/scala/example/StickyThread.scala
Labels: documentation

#598 ci(benchmark): optimise benchmark workflow
  .github/workflows/ci.yml
  build.sbt
  project/BenchmarkWorkFlow.scala
Labels: chore

#600 refactor: HttpsHelloWorld
  example/src/main/resources/localhost.cert
  example/src/main/resources/mysslstore.jks
  example/src/main/resources/server.crt
  example/src/main/resources/server.key
  example/src/main/scala/example/HttpsHelloWorld.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSSLHandler.scala
Labels: enhancement, automerge

#602 fix(Example): HttpsClient example fixed
  example/src/main/scala/example/HttpsClient.scala
Labels: bug, automerge

#603 fix(Endpoint): fix endpoint example
  example/src/main/scala/example/Endpoints.scala
Labels: documentation

#610 Update sbt to 1.5.6
  project/build.properties
Labels: automerge, chore

#609 Update netty-all to 4.1.71.Final
  project/Dependencies.scala
Labels: chore

#611 Update scalafix to 0.9.33
  project/plugins.sbt
Labels: bug, automerge, chore

#627 Chore: Update release drafter
  .github/release-drafter.yml
Labels: maintenance

#632 Documentation fix for `defaultWith`
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: bug, documentation, automerge

#523 Feature: Add `provide` operator on `Socket`
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: enhancement, automerge

#543 Feature: Add method for creating text/html response
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: enhancement

#654 Fix: Handle SSL failures
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/test/resources/cert.crt.pem
  zio-http/src/test/resources/keystore.jks
  zio-http/src/test/resources/server.crt
  zio-http/src/test/resources/server.key
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
Labels: bug

#662 Fix sbt warning for shell syntax deprecation
  build.sbt
Labels: automerge, maintenance

#663 Fix example links in readme
  README.md
Labels: documentation, automerge, maintenance

#651 Fix: UnsupportedOperationException when calling request.getBody on no…
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug, automerge

#664 update: automerge-action to 0.14.3
  .github/workflows/auto-merge.yml
Labels: maintenance

#649 Fix: Websocket upgrade when used with Http.collectM
  build.sbt
  project/Dependencies.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/WebsocketServerSpec.scala
Labels: bug, maintenance

#671 Update sbt to 1.5.8
  project/build.properties
Labels: maintenance

#667 Feature: Headers composition
  .scalafmt.conf
  example/src/main/scala/example/Authentication.scala
  example/src/main/scala/example/HelloWorld.scala
  example/src/main/scala/example/HelloWorldTwirl.scala
  example/src/main/scala/example/HelloWorldWithCORS.scala
  example/src/main/scala/example/HelloWorldWithMiddlewares.scala
  example/src/main/scala/example/HttpsClient.scala
  example/src/main/scala/example/HttpsHelloWorld.scala
  example/src/main/scala/example/SimpleClient.scala
  example/src/main/scala/example/StreamingResponse.scala
  zio-http/src/main/scala/zhttp/http/HasCookie.scala
  zio-http/src/main/scala/zhttp/http/Header.scala
  zio-http/src/main/scala/zhttp/http/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Method.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/Patch.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderChecks.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderConstructors.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderNames.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderValues.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/DecodeJResponse.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpAppTestExtensions.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/middleware/MiddlewareSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: maintenance

#678 Update sbt-updates to 0.6.1
  project/plugins.sbt
Labels: maintenance

#670 Move TechEmpowerBenchmark Server to this repo
  .github/workflows/ci.yml
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  project/BenchmarkWorkFlow.scala
Labels: maintenance

#681 Improve benchmark comment
  .github/workflows/ci.yml
  project/BenchmarkWorkFlow.scala
Labels: maintenance

#636 Refactor: Client Response Handler
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/DecodeJResponse.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/main/scala/zhttp/service/client/ClientChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zhttp/service/client/content/handlers/ClientResponseHandler.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: automerge, maintenance

#684 Doc: add documentation for Headers
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderChecks.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderConstructors.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderNames.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderValues.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
Labels: automerge, docs

#699 Update scoverage to 1.9.2
  .github/workflows/ci.yml
  project/BuildHelper.scala
  project/ScoverageWorkFlow.scala
Labels: maintenance

#698 chore: Ignore flaky tests
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
Labels: maintenance

#692 Feature: Support for Html Template
  .github/workflows/ci.yml
  example/src/main/scala/example/HtmlTemplating.scala
  project/ScoverageWorkFlow.scala
  zio-http/src/main/scala/zhttp/html/Attributes.scala
  zio-http/src/main/scala/zhttp/html/Dom.scala
  zio-http/src/main/scala/zhttp/html/Elements.scala
  zio-http/src/main/scala/zhttp/html/Html.scala
  zio-http/src/main/scala/zhttp/html/IsAttributeValue.scala
  zio-http/src/main/scala/zhttp/html/package.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/html/DomSpec.scala
  zio-http/src/test/scala/zhttp/html/HtmlSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: maintenance

#704 Rename HttpData.fromText to HttpData.fromString
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientParamsSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement

#690 Update sbt-scalafmt to 2.4.6
  project/plugins.sbt
Labels: maintenance

#688 Update scalafmt-core to 3.2.2
  .scalafmt.conf
  zio-http/src/main/scala/zhttp/http/PathModule.scala
Labels: maintenance

#710 Update scalafmt-core to 3.3.0
  .scalafmt.conf
Labels: maintenance

#711 Fix: Content-Length issues
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Patch.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientParamsSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: bug

#716 chore: ignore ClientHttpsSpec
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
Labels: maintenance

#661 `build.sbt` clean up
  aliases.sbt
  build.sbt
  global.sbt
  project/BuildHelper.scala
  project/Dependencies.scala
Labels: maintenance

#714 Remove Endpoint from Client.request
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: maintenance, Breaking Change

#723 Update sbt to 1.6.1
  project/build.properties
Labels: maintenance

#722 Chore: Ignore errors on Performance Server
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: maintenance

#721 fix: for escaping self closing tags
  zio-http/src/main/scala/zhttp/html/Dom.scala
  zio-http/src/main/scala/zhttp/html/Elements.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/html/DomSpec.scala
  zio-http/src/test/scala/zhttp/html/HtmlSpec.scala
Labels: bug

#728 fix: for failing doc generation
  zio-http/src/main/scala/zhttp/html/Dom.scala
Labels: bug, documentation

#730 Refactor: add HeaderNames and HeaderValues
  example/src/main/scala/example/HelloWorldTwirl.scala
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderChecks.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderConstructors.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderNames.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderValues.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement, maintenance
