Repository zio/zio-http, pull requests merged in 2022-07, with the labels that each got.

#1324 Update sbt-bloop to 1.5.2
  project/plugins.sbt
Labels: maintenance

#1323 Feature: add `contraCollect` in `Http`
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: enhancement

#1318 Feature: Add `seeOther` to `Response`
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: enhancement

#1319 Update README.md
  README.md
Labels: docs

#1327 chore: add `Debug.scala`
  build.sbt
  project/BuildHelper.scala
  project/Debug.scala
Labels: maintenance

#1326 Fix: `fireExceptionCaught` from `HttpRuntime`
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
Labels: bug

#1328 Refactor: add more colors to `LogFormat`
  zio-http-logging/src/main/scala/zhttp/logging/LogFormat.scala
Labels: maintenance

#1329 Feature: add support to pass `Headers` in `SocketApp.connect`
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
Labels: enhancement

#1325 Refactor: Redesign WebSocket API
  docs/website/docs/v1.x/dsl/socket/socket.md
  example/src/main/scala/example/AuthenticationServer.scala
  example/src/main/scala/example/BasicAuth.scala
  example/src/main/scala/example/WebSocketAdvanced.scala
  example/src/main/scala/example/WebSocketEcho.scala
  example/src/main/scala/example/WebSocketSimpleClient.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Channel.scala
  zio-http/src/main/scala/zhttp/service/ChannelEvent.scala
  zio-http/src/main/scala/zhttp/service/ChannelFactory.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/Logging.scala
  zio-http/src/main/scala/zhttp/service/WebSocketAppHandler.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/main/scala/zhttp/socket/IsWebSocket.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
  zio-http/src/main/scala/zhttp/socket/package.scala
  zio-http/src/test/scala/zhttp/internal/DynamicServer.scala
  zio-http/src/test/scala/zhttp/internal/package.scala
  zio-http/src/test/scala/zhttp/service/ChannelSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketSpec.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: maintenance, docs, Breaking Change

#1353 Feature: Add `toJavaURI` and `toJavaURL` to `URL`
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: enhancement

#1355 Fix: Allow multiple `set-cookie` headers in response
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: bug

#1358 Doc: Fix links in Readme and add more examples
  README.md
Labels: bug, docs

#1366 Refactor: Drop test composition syntax
  zio-http/src/test/scala/zhttp/html/DomSpec.scala
  zio-http/src/test/scala/zhttp/html/HtmlGen.scala
  zio-http/src/test/scala/zhttp/html/HtmlSpec.scala
  zio-http/src/test/scala/zhttp/http/ContentTypeSpec.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/http/EncodeRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/http/HExitSpec.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpErrorSpec.scala
  zio-http/src/test/scala/zhttp/http/MiddlewareSpec.scala
  zio-http/src/test/scala/zhttp/http/ProxySpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
  zio-http/src/test/scala/zhttp/http/SchemeSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/AuthSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CorsSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CsrfSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/KeepAliveSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticServerSpec.scala
Labels: bug

#1379 Fix: Propagate `FiberRef` To `HttpRuntime`
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
Labels: bug

#1380 chore: drop sbt bloop
  project/plugins.sbt
Labels: maintenance

#1364 Fix: Client fails when connection is interrupted
  zio-http/src/main/scala/zhttp/service/Client.scala
Labels: bug
