Repository zio/zio-http, pull requests merged in 2022-09, with the labels that each got.

#1419 Update scala3-library to 3.2.0
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: maintenance

#1415 Feature: Improve `cookie` ergonomics
  example/src/main/scala/example/CookieServerSide.scala
  example/src/main/scala/example/SignCookies.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/CookieDecodeBenchmark.scala
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/CookieDecoder.scala
  zio-http/src/main/scala/zhttp/http/CookieEncoder.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderConstructors.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CsrfSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: enhancement, Breaking Change

#1409 Fix: CORS Headers implementation
  zio-http/src/main/scala/zio/http/Headers.scala
  zio-http/src/main/scala/zio/http/middleware/Cors.scala
  zio-http/src/test/scala/zio/http/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zio/http/middleware/CorsSpec.scala
  zio-http/src/test/scala/zio/http/service/ServerSpec.scala
  zio-http/src/test/scala/zio/http/service/StaticServerSpec.scala
Labels: bug

#1446 Doc: Update README.md
  README.md
Labels: documentation

#1458 Fix: Do not escape valid headers
  zio-http/src/main/scala/zio/http/Headers.scala
  zio-http/src/test/scala/zio/http/HeaderSpec.scala
Labels: bug

#1444 Refactor: Rename `Server.error` to `Server.onError`
  zio-http-example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zio/http/Server.scala
Labels: enhancement, Breaking Change

#1467 ZIO logger based logger transport and request logging middleware
  build.sbt
  zio-http-logging/src/main/scala/zio/logging/Logger.scala
  zio-http-logging/src/main/scala/zio/logging/LoggerTransport.scala
  zio-http-logging/src/test/scala/zio/logging/LoggerSpec.scala
  zio-http/src/main/scala/zio/http/middleware/RequestLogging.scala
  zio-http/src/main/scala/zio/http/middleware/Web.scala
Labels: maintenance

#1504 fix: Publish settings
  project/BuildHelper.scala
Labels: bug, maintenance

#1508 Fix: Documentation website deployment
  .github/workflows/ci.yml
  build.sbt
  docs/index.md
  docs/website/package.json
  docs/website/yarn.lock
Labels: bug, maintenance, docs

#1509 Update README.md for latest snapshot and release version
  README.md
Labels: docs

#1543 fix client request in case of streaming.
  zio-http/src/main/scala/zio/http/netty/client/ClientInboundStreamingHandler.scala
Labels: bug

#1534 Abstract away netty.2
  .github/workflows/ci.yml
  benchmark-zio-http.sh
  project/BenchmarkWorkFlow.scala
  project/ScalaSettings.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpCollectEval.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpRouteTextPerf.scala
  zio-http-example/src/main/scala/example/APIExamples.scala
  zio-http-example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zio/http/Body.scala
  zio-http/src/main/scala/zio/http/Http.scala
  zio-http/src/main/scala/zio/http/Request.scala
  zio-http/src/main/scala/zio/http/ZClient.scala
  zio-http/src/main/scala/zio/http/api/internal/APIClient.scala
  zio-http/src/main/scala/zio/http/model/Version.scala
  zio-http/src/main/scala/zio/http/netty/EventLoopGroups.scala
  zio-http/src/main/scala/zio/http/netty/Versions.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientInboundStreamingHandler.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientRequestEncoder.scala
  zio-http/src/main/scala/zio/http/netty/package.scala
  zio-http/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
  zio-http/src/test/scala/zio/http/ClientRequestEncoderSpec.scala
  zio-http/src/test/scala/zio/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zio/http/RequestSpec.scala
  zio-http/src/test/scala/zio/http/StatusSpec.scala
  zio-http/src/test/scala/zio/http/api/InSpec.scala
  zio-http/src/test/scala/zio/http/internal/HttpGen.scala
  zio-http/src/test/scala/zio/http/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zio/http/middleware/AuthSpec.scala
  zio-http/src/test/scala/zio/http/middleware/CorsSpec.scala
  zio-http/src/test/scala/zio/http/middleware/CsrfSpec.scala
  zio-http/src/test/scala/zio/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zio/http/netty/VersionsSpec.scala
  zio-http/src/test/scala/zio/http/service/ClientProxySpec.scala
  zio-http/src/test/scala/zio/http/service/RequestStreamingServerSpec.scala
Labels: maintenance
