Repository zio/zio-http, pull requests merged in 2022-05, with the labels that each got.

#1243 Refactor: rename property in `Server.Config`
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: refactor

#1242 Fix: Request Streaming
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug

#1244 Fix: Echo `HttpData` directly from `Request`
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/RequestBodyHandler.scala
  zio-http/src/main/scala/zhttp/service/ServerResponseWriter.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug

#1188 Fix: Request Streaming back pressure
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/service/RequestBodyHandler.scala
  zio-http/src/test/resources/1M.img
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
  zio-http/src/test/scala/zhttp/service/RequestStreamingServerSpec.scala
Labels: bug

#1255 chore: Remove unnecessary dependencies
  build.sbt
  project/Dependencies.scala
Labels: maintenance

#1259 Refactor: Client.socket now returns a `ZManaged`
  example/src/main/scala/example/WebSocketSimpleClient.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: enhancement, Breaking Change

#1264 Refactor: Drop `Endpoint` API
  example/src/main/scala/example/Endpoints.scala
  zio-http/src/main/scala/zhttp/endpoint/CanCombine.scala
  zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala
  zio-http/src/main/scala/zhttp/endpoint/CanExtract.scala
  zio-http/src/main/scala/zhttp/endpoint/Endpoint.scala
  zio-http/src/main/scala/zhttp/endpoint/Parameter.scala
  zio-http/src/main/scala/zhttp/endpoint/ParameterList.scala
  zio-http/src/main/scala/zhttp/endpoint/TupleBuilder.scala
  zio-http/src/main/scala/zhttp/endpoint/package.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala
  zio-http/src/test/scala/zhttp/http/RequestSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: enhancement, maintenance, Breaking Change

#1269 Fix: Middleware type issues
  zio-http/src/main/scala/zhttp/http/IsMono.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/main/scala/zhttp/http/middleware/package.scala
  zio-http/src/test/scala/zhttp/http/MiddlewareSpec.scala
Labels: bug, Breaking Change, ready

#1270 Update scalafmt-core to 3.5.5
  .scalafmt.conf
  example/src/main/scala/example/HelloWorldWithMiddlewares.scala
Labels: maintenance

#1115 Maintenance: Add internal Logging capabilities using `zhttp.log`
  .github/workflows/ci.yml
  build.sbt
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  project/BuildHelper.scala
  project/Dependencies.scala
  project/ScalaSettings.scala
  zio-http-logging/src/main/scala-2/zhttp/logging/macros/LoggerMacroExtensions.scala
  zio-http-logging/src/main/scala-2/zhttp/logging/macros/LoggerMacroImpl.scala
  zio-http-logging/src/main/scala-3/zhttp/logging/macros/LoggerMacroExtensions.scala
  zio-http-logging/src/main/scala-3/zhttp/logging/macros/LoggerMacroImpl.scala
  zio-http-logging/src/main/scala/zhttp/logging/LogFormat.scala
  zio-http-logging/src/main/scala/zhttp/logging/LogLevel.scala
  zio-http-logging/src/main/scala/zhttp/logging/LogLine.scala
  zio-http-logging/src/main/scala/zhttp/logging/Logger.scala
  zio-http-logging/src/main/scala/zhttp/logging/LoggerTransport.scala
  zio-http-logging/src/test/scala/zhttp/logging/LogLevelSpec.scala
  zio-http-logging/src/test/scala/zhttp/logging/LoggerSpec.scala
  zio-http/src/main/scala/zhttp/html/Html.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/Logging.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/ServerResponseWriter.scala
  zio-http/src/main/scala/zhttp/service/logging/NettyLoggerFactory.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/LogLevelTransform.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: maintenance, docs

#1266 Fix: Use `check` instead of `checkAll`
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/test/scala/zhttp/html/DomSpec.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug, Breaking Change

#1271 Refactor: drop `Http.route`
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: enhancement, maintenance, Breaking Change

#999 Doc: Middleware
  docs/website/docs/v1.x/dsl/middleware.md
Labels: documentation, docs

#1273 Update scalafmt-core to 3.5.7
  .scalafmt.conf
Labels: maintenance

#1107 Performance: Improve Scheme.decode performance
  .github/workflows/ci.yml
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/SchemeDecodeBenchmark.scala
  zio-http/src/main/scala/zhttp/http/Scheme.scala
  zio-http/src/test/scala/zhttp/http/SchemeSpec.scala
Labels: enhancement, maintenance, performance, ready, run jmh

#1260 Refactor: Re-write `Path` using `Vector`
  example/src/main/scala/example/ConcreteEntity.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/CookieDecodeBenchmark.scala
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Path.scala
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/main/scala/zhttp/http/PathSyntax.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/ServerResponseWriter.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: bug, performance, refactor, Breaking Change, run jmh
