Repository zio/zio-http, pull requests merged in 2022-10, with the labels that each got.

#1650 Add profiling setup.
  .gitignore
  benchmark-zio-http.sh
  profiling/Dockerfile
  profiling/README.md
  profiling/build-docker-image.sh
  profiling/build.sbt
  profiling/project/build.properties
  profiling/project/plugins.sbt
  profiling/run-zio-http.sh
Labels: maintenance, docs

#1493 Client connection pools
  build.sbt
  project/Dependencies.scala
  project/ScalaSettings.scala
  zio-http-example/src/main/scala/example/ClientWithDecompression.scala
  zio-http-example/src/main/scala/example/HttpsClient.scala
  zio-http/src/main/scala/zio/http/Channel.scala
  zio-http/src/main/scala/zio/http/ClientConfig.scala
  zio-http/src/main/scala/zio/http/ConnectionPoolConfig.scala
  zio-http/src/main/scala/zio/http/Response.scala
  zio-http/src/main/scala/zio/http/ZClient.scala
  zio-http/src/main/scala/zio/http/netty/NettyFutureExecutor.scala
  zio-http/src/main/scala/zio/http/netty/client/ChannelState.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientInboundStreamingHandler.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientResponseStreamHandler.scala
  zio-http/src/main/scala/zio/http/netty/client/ConnectionPool.scala
  zio-http/src/test/scala/zio/http/BodySpec.scala
  zio-http/src/test/scala/zio/http/SSLSpec.scala
  zio-http/src/test/scala/zio/http/api/ServerClientIntegrationSpec.scala
  zio-http/src/test/scala/zio/http/internal/HttpGen.scala
  zio-http/src/test/scala/zio/http/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zio/http/service/ClientProxySpec.scala
  zio-http/src/test/scala/zio/http/service/ClientSpec.scala
  zio-http/src/test/scala/zio/http/service/ClientStreamingSpec.scala
  zio-http/src/test/scala/zio/http/service/ConnectionPoolSpec.scala
  zio-http/src/test/scala/zio/http/service/KeepAliveSpec.scala
  zio-http/src/test/scala/zio/http/service/WebSocketSpec.scala
Labels: maintenance

#1394 feat: add metrics middleware
  build.sbt
  zio-http/src/main/scala/zio/http/middleware/Metrics.scala
  zio-http/src/main/scala/zio/http/middleware/Web.scala
  zio-http/src/test/scala/zio/http/middleware/MetricsSpec.scala
Labels: enhancement
