Repository zio/zio-http, pull requests merged in 2022-04, with the labels that each got.

#1175 Fix: update implementation of `FromAsciiString.encode`
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug

#1135 Added workflow for Jmh benchmarks
  .github/workflows/ci.yml
  build.sbt
  project/BuildHelper.scala
  project/JmhBenchmarkWorkflow.scala
Labels: enhancement, maintenance, ready, run jmh

#1157 Feature: add `delay` `tap` operator to Socket
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: enhancement, ready

#1196 Fix: Getting started doc broken links fixed
  docs/website/docs/v1.x/getting-started.md
Labels: bug, docs, ready

#1203 Update scala3-library to 3.1.2
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: maintenance

#1204 Feature: Add implicit conversion from `Unit` to `Html`
  zio-http/src/main/scala/zhttp/html/Html.scala
  zio-http/src/test/scala/zhttp/html/HtmlSpec.scala
Labels: enhancement, ready

#1156 Fix: Handle on-close interruption in websocket
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/WebSocketAppHandler.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: bug, ready

#1177 maintenance: bump version in website docs
  docs/website/docs/v1.x/index.md
Labels: docs

#1198 Refactor: ServerResponseHandler
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/ServerResponseWriter.scala
  zio-http/src/main/scala/zhttp/service/package.scala
Labels: enhancement, ready

#1218 Update scalafmt-core to 3.5.2
  .scalafmt.conf
Labels: maintenance

#1224 Update sbt-bloop to 1.5.0
  project/plugins.sbt
Labels: maintenance

#1210 Feat: added option to modify server bootstrap
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: enhancement

#1223 refactor: move logic to ServerResponseWriter
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/ServerResponseWriter.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: refactor, ready

#1232 Feature: Add `merge` operator in `Http`
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: enhancement, ready
