Repository zio/zio-http, pull requests merged in 2022-06, with the labels that each got.

#1284 Update scalafmt-core to 3.5.8
  .scalafmt.conf
Labels: maintenance

#1287 publish: zio-logging
  build.sbt
Labels: maintenance

#1277 Update sbt-updates to 0.6.3
  project/plugins.sbt
Labels: maintenance

#1302 Fix: Native EPoll and KQueue Dependencies
  project/Dependencies.scala
Labels: bug

#1298 Fix: Logging Checks
  build.sbt
  project/BuildHelper.scala
  zio-http-logging/src/main/scala-2/zhttp/logging/macros/LoggerMacroImpl.scala
  zio-http-logging/src/main/scala/zhttp/logging/Font.scala
  zio-http-logging/src/main/scala/zhttp/logging/LogFormat.scala
  zio-http-logging/src/main/scala/zhttp/logging/LogLevel.scala
  zio-http-logging/src/main/scala/zhttp/logging/Logger.scala
  zio-http-logging/src/main/scala/zhttp/logging/LoggerTransport.scala
  zio-http-logging/src/test/scala/zhttp/logging/LogLevelSpec.scala
  zio-http-logging/src/test/scala/zhttp/logging/LoggerSpec.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/Logging.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: bug, maintenance

#1306 Fix: Return empty URL in case of a parse failure
  zio-http/src/main/scala/zhttp/service/Handler.scala
Labels: bug

#1311 Refactor: Remove `zhttp-test` module
  .github/workflows/ci.yml
  build.sbt
  docs/index.md
  zio-http-test/src/main/scala/zhttp/test/test.scala
Labels: maintenance, docs

#1297 Update sbt-scalafix to 0.10.1
  project/plugins.sbt
Labels: bug, maintenance

#1312 Update scala3-library to 3.1.3
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: maintenance

#1288 Fix: Cookie expires format
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: bug

#1304 Fix: Support trailing and leading slashes in `Path`
  example/src/main/scala/example/StaticServer.scala
  zio-http/src/main/scala/zhttp/http/Path.scala
  zio-http/src/main/scala/zhttp/http/PathSyntax.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: bug, Breaking Change

#1291 Feature: Middleware for TrailingSlash
  zio-http/src/main/scala/zhttp/http/Path.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
Labels: bug, enhancement
