Repository zio/zio-http, pull requests merged in 2022-03, with the labels that each got.

#1109 Removed flatten from test
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: enhancement, maintenance

#1048 Feature: Request Streaming
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/RequestBodyHandler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticServerSpec.scala
Labels: enhancement, Breaking Change, ready

#1118 Fix toByteBuf for streamed HttpData
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
Labels: bug

#1120 Example: more secure string compare for login
  example/src/main/scala/example/Authentication.scala
Labels: documentation

#1083 Feature: Introduced defect channel for `Http`
  zio-http/src/main/scala/zhttp/http/HExit.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/test/scala/zhttp/http/HExitAssertion.scala
  zio-http/src/test/scala/zhttp/http/HExitSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
  zio-http/src/test/scala/zhttp/internal/DynamicServer.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticServerSpec.scala
Labels: enhancement

#1111 Enhancement: Merge server and client Responses
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/IsResponse.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: enhancement

#1127 Refactor: remove links from scaladoc
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: enhancement, maintenance

#1094 Feature: Add `version` to `Request`
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpRouteTextPerf.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: enhancement, Breaking Change, ready

#1125 Refactor: Merge client and server `Request`
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/main/scala/zhttp/service/HttpMessageCodec.scala
  zio-http/src/test/scala/zhttp/http/EncodeRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: enhancement, refactor, Breaking Change, ready

#1128 Refactor: Http.Status names to Camel Case
  example/src/main/scala/example/StreamingResponse.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/Status.scala
  zio-http/src/main/scala/zhttp/http/middleware/Auth.scala
  zio-http/src/main/scala/zhttp/http/middleware/Cors.scala
  zio-http/src/main/scala/zhttp/http/middleware/Csrf.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/AuthSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CorsSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CsrfSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: Breaking Change, ready

#1129 Refactor: Http.Status names to Camel Case
  example/src/main/scala/example/StreamingResponse.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/Status.scala
  zio-http/src/main/scala/zhttp/http/middleware/Auth.scala
  zio-http/src/main/scala/zhttp/http/middleware/Cors.scala
  zio-http/src/main/scala/zhttp/http/middleware/Csrf.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpErrorSpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/AuthSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CorsSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CsrfSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: refactor, Breaking Change

#1121 Feature: Support Custom statuses code
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/test/scala/zhttp/http/HttpErrorSpec.scala
Labels: enhancement

#1105 Refactor: Added lift in PartialCollect
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpCollectEval.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: enhancement, maintenance, performance

#1113 Refactor: Make `Http.getResource` consistent with `ZStream.fromResource`
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/ContentTypeSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
Labels: refactor, Breaking Change

#1137 Performance: Improve HttpData toByteBuf
  example/src/main/scala/example/StaticServer.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
Labels: enhancement, maintenance, blocker, ready

#1039 Fix: Handle HttpClient Interruption on connection close
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
Labels: bug

#1141 Feature: add `Middleware.codecHttp`
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
  zio-http/src/test/scala/zhttp/http/MiddlewareSpec.scala
Labels: enhancement, ready

#1142 Performance: Use `CharSequence` internally wherever possible
  zio-http/src/main/scala/zhttp/html/Dom.scala
  zio-http/src/main/scala/zhttp/html/Elements.scala
  zio-http/src/main/scala/zhttp/html/Html.scala
  zio-http/src/main/scala/zhttp/html/Template.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/HttpDataExtension.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
  zio-http/src/test/scala/zhttp/html/DomSpec.scala
Labels: enhancement, maintenance

#1161 feature: add `narrow` operator to Http
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: ready

#1160 feature: add `toHttp` method to `Response`
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: ready

#1159 refactor: DynamicServer is not bound to HttpEnv only
  zio-http/src/test/scala/zhttp/internal/DynamicServer.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/internal/package.scala
Labels: ready

#1158 Fix: `Socket.end` implementation
  zio-http/src/main/scala/zhttp/socket/Socket.scala
Labels: bug, ready

#1163 Update sbt-scala3-migrate to 0.5.1
  project/plugins.sbt
Labels: maintenance
