Repository zio/zio-http, pull requests merged in 2022-02, with the labels that each got.

#920 Update scalafmt-core to 3.4.0
  .scalafmt.conf
Labels: maintenance

#940 Remove outdated benchmark.md
  BENCHMARKS.md
  README.md
Labels: maintenance, docs

#928 refactor: rename `getHeaders` to `headers` in `ClientRequest`
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
Labels: maintenance, Breaking Change, ready

#927 Refactor: rename `asString` to `encode` in `Path`
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: refactor, Breaking Change, ready

#854 BenchMarks: Disable flow Control
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: bug, ready

#888 Documentation: Http
  docs/website/docs/v1.x/dsl/http/index.md
Labels: documentation, docs

#950 Refactor: Drop `toZIO` and `wrapZIO` APIs
  docs/website/docs/v1.x/examples/advanced-examples/web-socket-advanced.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/web-socket.md
  docs/website/docs/v1.x/getting-started.md
  example/src/main/scala/example/WebSocketAdvanced.scala
  example/src/main/scala/example/WebSocketEcho.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
Labels: enhancement, maintenance, refactor, docs, ready

#792 Fix: Server KeepAlive true by default and enable client to set Http version on requests
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/KeepAliveSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: bug, ready

#946 feat: url add `isAbsolute` and `isRelative` operators
  zio-http/src/main/scala/zhttp/http/URL.scala
Labels: enhancement, ready

#926 Documentation: Request
  docs/website/docs/v1.x/dsl/request/index.md
Labels: documentation, docs

#952 Add host and port hint in client ssl context
  zio-http/src/main/scala/zhttp/service/Client.scala
Labels: bug, ready

#955 feature: add connect operator on Socket
  zio-http/src/main/scala/zhttp/socket/Socket.scala
Labels: enhancement, ready

#959 Style: Update scala doc wrapping
  .scalafmt.conf
  example/src/main/scala/example/HttpsHelloWorld.scala
  zio-http/src/main/scala/zhttp/html/Dom.scala
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/HExit.scala
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/RouteDecoderModule.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderChecks.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderConstructors.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderExtension.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderNames.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderValues.scala
  zio-http/src/main/scala/zhttp/http/middleware/Auth.scala
  zio-http/src/main/scala/zhttp/http/middleware/Csrf.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/main/scala/zhttp/service/ChannelFuture.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/WebSocketAppHandler.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/main/scala/zhttp/socket/SocketDecoder.scala
  zio-http/src/main/scala/zhttp/socket/SocketProtocol.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: maintenance, docs, ready

#958 Refactor: Remove `get` prefix from Public APIs
  example/src/main/scala/example/Authentication.scala
  example/src/main/scala/example/HttpsClient.scala
  example/src/main/scala/example/SimpleClient.scala
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/IsResponse.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderChecks.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/middleware/Auth.scala
  zio-http/src/main/scala/zhttp/http/middleware/Cors.scala
  zio-http/src/main/scala/zhttp/http/middleware/Csrf.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientRequest.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/AuthSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CorsSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/CsrfSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zhttp/internal/DynamicServer.scala
  zio-http/src/test/scala/zhttp/internal/HttpAppTestExtensions.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/KeepAliveSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: refactor, Breaking Change, ready

#957 Refactor: Remove declarative API from Middlewares
  zio-http/src/main/scala/zhttp/http/Middleware.scala
Labels: enhancement, ready

#970 Doc: Readme
  README.md
Labels: docs

#963 style: rearrange methods in files
  zio-http/src/main/scala/zhttp/http/Headers.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Method.scala
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderConstructors.scala
Labels: style, ready

#974 Doc: Cookie
  docs/website/docs/v1.x/dsl/cookies/index.md
Labels: documentation, docs

#980 Fix: Fire response instead of error in HExit.Failure()
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug, ready

#981 fix: typo in bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, docs

#984 Refactor: remove sealed modifier from Middleware trait
  zio-http/src/main/scala/zhttp/http/Middleware.scala
Labels: enhancement, ready

#985 Refactor: Rename `getBodyAsByteBuf` to `bodyAsByteBuf` method on Client
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientRequest.scala
Labels: refactor

#989 Fix: Request doc
  docs/website/docs/v1.x/dsl/request/index.md
Labels: bug, docs

#992 Fix: Gen without HEAD for Responses with content
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug

#988 doc: setup g8
  docs/website/docs/v1.x/index.md
Labels: docs

#953 Doc: for WebSocketFrame
  docs/website/docs/v1.x/dsl/socket/index.md
  docs/website/docs/v1.x/dsl/socket/websocketframe.md
Labels: documentation, docs, ready

#987 Documentation for HttpData
  docs/website/docs/v1.x/dsl/http-data/index.md
Labels: docs

#996 refactor: rename `provide` and `provideSome`
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: maintenance, Breaking Change

#899 Fix: `Content-Type` header gets incorrect values.
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/ProbeContentTypeBenchmark.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/MediaType.scala
  zio-http/src/main/scala/zhttp/http/MimeDB.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/resources/TestFile2.mp4
  zio-http/src/test/resources/TestFile3.js
  zio-http/src/test/resources/TestFile4
  zio-http/src/test/resources/TestFile5.css
  zio-http/src/test/resources/TestFile6.mp3
  zio-http/src/test/scala/zhttp/http/ContentTypeSpec.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug

#986 Feat: Http from HExit
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement

#1002 Refactor: Remove Collect and FromFunctionZIO
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: enhancement, maintenance

#1010 Feature: add `fromFileZIO`
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: enhancement, ready

#1011 Refactor: `fromFile` uses `fromFileZIO`
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: refactor, ready

#1008 Refactor: Content Type Fixes
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/MediaType.scala
  zio-http/src/main/scala/zhttp/http/MimeDB.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/http/ContentTypeSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: bug, refactor, ready

#1014 doc: fix binary constructor usage
  docs/website/docs/v1.x/dsl/socket/websocketframe.md
Labels: documentation, docs

#1017 Feature: Add `data` in `Request` trait
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
Labels: enhancement, ready

#1027 maintenance: run scalafmt once
  .github/workflows/ci.yml
  build.sbt
Labels: maintenance, ready

#1022 Update scalafmt-core to 3.4.3
  .scalafmt.conf
Labels: maintenance

#1033 Remove tuple from ResponseHandler
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
Labels: refactor, ready

#1041 cherry pick websocket binary fix changes from main
  docs/website/docs/v1.x/dsl/socket/index.md
  docs/website/docs/v1.x/dsl/socket/websocketframe.md
  zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: bug, Breaking Change, ready

#1040 Restructuring website nav drawer
  docs/website/docs/v1.x/dsl/cookies.md
  docs/website/docs/v1.x/dsl/cookies/_category_.json
  docs/website/docs/v1.x/dsl/headers.md
  docs/website/docs/v1.x/dsl/headers/_category_.json
  docs/website/docs/v1.x/dsl/http-data/_category_.json
  docs/website/docs/v1.x/dsl/http-endpoint/_category_.json
  docs/website/docs/v1.x/dsl/http-endpoint/index.md
  docs/website/docs/v1.x/dsl/http.md
  docs/website/docs/v1.x/dsl/http/_category_.json
  docs/website/docs/v1.x/dsl/httpdata.md
  docs/website/docs/v1.x/dsl/middleware.md
  docs/website/docs/v1.x/dsl/middleware/_category_.json
  docs/website/docs/v1.x/dsl/middleware/index.md
  docs/website/docs/v1.x/dsl/request.md
  docs/website/docs/v1.x/dsl/request/_category_.json
  docs/website/docs/v1.x/dsl/response.md
  docs/website/docs/v1.x/dsl/response/_category_.json
  docs/website/docs/v1.x/dsl/response/index.md
  docs/website/docs/v1.x/dsl/server.md
  docs/website/docs/v1.x/dsl/server/_category_.json
Labels: documentation, docs, ready

#1038 Added more examples in documentation
  docs/website/docs/v1.x/examples/advanced-examples/advanced_server.md
  docs/website/docs/v1.x/examples/advanced-examples/middleware_basic_auth.md
  docs/website/docs/v1.x/examples/advanced-examples/middleware_cors.md
  docs/website/docs/v1.x/examples/advanced-examples/middleware_csrf.md
  docs/website/docs/v1.x/examples/advanced-examples/web-socket-advanced.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/http_client.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/http_server.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/https_client.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/https_server.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/web-socket.md
Labels: documentation, docs, ready

#967 Doc: Response
  docs/website/docs/v1.x/dsl/response.md
Labels: documentation, docs, ready

#1047 Doc: Renamed sections
  docs/website/docs/v1.x/dsl/http.md
  docs/website/docs/v1.x/dsl/server.md
Labels: docs, ready

#1046 Fix: Releasing request twice
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
Labels: bug

#1035 Tail recursive path encode method
  zio-http/src/main/scala/zhttp/http/PathModule.scala
Labels: ready

#1024 Feature: Static Server
  example/src/main/resources/TestStatic/Dummy.txt
  example/src/main/resources/TestStatic/Nested/TestFile.txt
  example/src/main/scala/example/FileStreaming.scala
  example/src/main/scala/example/StaticServer.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/ProbeContentTypeBenchmark.scala
  zio-http/src/main/scala/zhttp/core/Util.scala
  zio-http/src/main/scala/zhttp/html/StyledContainerHtml.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/MediaType.scala
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
  zio-http/src/test/resources/TestStatic/Folder2/TestFile2.txt
  zio-http/src/test/resources/TestStatic/TestFile1.txt
  zio-http/src/test/scala/zhttp/http/ContentTypeSpec.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
Labels: docs

#1064 Performance: Use `CharSequence` for ServerTime
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/server/ServerTime.scala
  zio-http/src/main/scala/zhttp/service/server/ServerTimeGenerator.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
Labels: performance, ready

#1065 Feature: add `dropLast` to Path
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/test/scala/zhttp/http/PathSpec.scala
Labels: enhancement, ready

#1067 Feature: `Response.html` support taking in a `Status`
  zio-http/src/main/scala/zhttp/http/Response.scala
Labels: ready

#1068 Feature: add `code` method on Status
  zio-http/src/main/scala/zhttp/http/Status.scala
Labels: enhancement, ready

#1073 Fix: type info of `Http.response`
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: bug, ready

#1066 Feature: add `foldCause` to HttpError
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/test/scala/zhttp/http/HttpErrorSpec.scala
Labels: enhancement, ready

#1071 Feature: add `withMediaType` operator in `HeaderModifier`
  zio-http/src/main/scala/zhttp/http/headers/HeaderModifier.scala
Labels: enhancement, ready

#1070 Feature: add `Http.attempt` operator
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: enhancement, ready

#1074 Feature: add `getResource` and `getResourceAsFile` operators on Http
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: enhancement, ready

#1055 Update sbt-bloop to 1.4.13
  project/plugins.sbt
Labels: maintenance

#1075 Feature: add `ifModifiedSinceDecoded`
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
Labels: enhancement, ready

#1061 Feature: Static Server
  example/src/main/resources/TestStatic/Dummy.txt
  example/src/main/resources/TestStatic/Nested/TestFile.txt
  example/src/main/scala/example/FileStreaming.scala
  example/src/main/scala/example/StaticServer.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/ProbeContentTypeBenchmark.scala
  zio-http/src/main/scala/zhttp/core/Util.scala
  zio-http/src/main/scala/zhttp/html/Template.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/MediaType.scala
  zio-http/src/main/scala/zhttp/http/PathModule.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
  zio-http/src/test/resources/TestStatic/Folder2/TestFile2.txt
  zio-http/src/test/resources/TestStatic/TestFile1.txt
  zio-http/src/test/scala/zhttp/http/ContentTypeSpec.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
Labels: docs

#932 Feature: Support custom `ChannelInitializer`
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
Labels: enhancement

#1036 doc: socket
  docs/website/docs/v1.x/dsl/socket/socket.md
Labels: documentation, docs, ready

#1077 Feature: add `fromHExit` constructor
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: enhancement, ready

#1078 Feature: Add `when` operator in `Http`
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: performance, ready

#1079 Feature: Effectful Auth Middleware
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/main/scala/zhttp/http/middleware/Auth.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/AuthSpec.scala
Labels: enhancement

#1053 Test: Server Settings Support in `HttpRunnableSpec#serve`
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: enhancement, ready

#1049 refactor: website docs sidebar pages repositioned
  docs/website/docs/v1.x/dsl/cookies.md
  docs/website/docs/v1.x/dsl/headers.md
  docs/website/docs/v1.x/dsl/http.md
  docs/website/docs/v1.x/dsl/httpdata.md
  docs/website/docs/v1.x/dsl/middleware.md
  docs/website/docs/v1.x/dsl/request.md
  docs/website/docs/v1.x/dsl/response.md
  docs/website/docs/v1.x/dsl/server.md
  docs/website/docs/v1.x/dsl/socket/_category_.json
Labels: documentation, maintenance, docs, ready

#1095 Feat: Server Request Decompression
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement

#1099 Fix: Capture synchronous defects inside Handler
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticServerSpec.scala
Labels: bug, ready
