Repository zio/zio-http, pull requests merged in 2022-01, with the labels that each got.

#744 Update scalafmt-core to 3.3.1
  .scalafmt.conf
  aliases.sbt
  global.sbt
  zio-http/src/main/scala/zhttp/http/Middleware.scala
Labels: maintenance

#706 Feature: Serve static files Asynchronously
  build.sbt
  example/src/main/resources/TestFile.txt
  example/src/main/resources/TestVideoFile.mp4
  example/src/main/scala/example/FileStreaming.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/resources/TestFile
  zio-http/src/test/resources/TestFile.txt
  zio-http/src/test/scala/zhttp/http/EncodeClientParamsSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement

#576 Reduce decodeResponseCookie allocations
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/CookieDecodeBenchmark.scala
  zio-http/src/main/scala/zhttp/http/Cookie.scala
Labels: performance

#750 Response Json headers
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala
Labels: bug

#542 feat(CSRF): add middleware for CSRF handling
  example/src/main/scala/example/CSRF.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/test/scala/zhttp/middleware/MiddlewareSpec.scala
Labels: enhancement

#739 Refactor: follow ZIO 2.0 naming conventions
  example/src/main/scala/example/HelloWorldAdvanced.scala
  example/src/main/scala/example/HelloWorldWithMiddlewares.scala
  zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala
  zio-http/src/main/scala/zhttp/http/HExit.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
  zio-http/src/test/scala/zhttp/middleware/MiddlewareSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement, maintenance, Breaking Change

#760 Remove @@ feature for cookies
  example/src/main/scala/example/CookieServerSide.scala
  zio-http/src/main/scala/zhttp/http/Cookie.scala
Labels: maintenance, refactor, Breaking Change

#762 Refactor: Use builder pattern for SocketApp
  example/src/main/scala/example/WebSocketAdvanced.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/main/scala/zhttp/socket/IsWebSocket.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: enhancement, Breaking Change

#763 Feature: Add `provide` operator on SocketApp
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
Labels: enhancement

#766 Refactor: Remove type params from HttpData
  example/src/main/scala/example/FileStreaming.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: enhancement, maintenance, Breaking Change

#761 Feature: CSRF Middleware
  example/src/main/scala/example/CSRF.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/test/scala/zhttp/middleware/MiddlewareSpec.scala
Labels: enhancement

#749 Fix: Endpoint fix in `to` operator
  example/src/main/scala/example/Endpoints.scala
  zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala
  zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala
Labels: bug

#682 Feature: Return `Start` on server start
  example/src/main/scala/example/HelloWorldAdvanced.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/test/scala/zhttp/internal/AppCollection.scala
  zio-http/src/test/scala/zhttp/internal/DynamicServer.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/internal/package.scala
  zio-http/src/test/scala/zhttp/service/ClientHttpsSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: enhancement

#771 Scala doc generation CI step
  .github/workflows/ci.yml
  build.sbt
  zio-http/src/main/scala/zhttp/http/Middleware.scala
Labels: bug, maintenance

#774 Maintenance: remove twirl settings and examples
  build.sbt
  example/src/main/scala/example/HelloWorldTwirl.scala
  example/src/main/scala/zhttp/nav/Navigation.scala
  example/src/main/twirl/advanced/button.scala.html
  example/src/main/twirl/advanced/index.scala.html
  example/src/main/twirl/advanced/renderNav.scala.html
  example/src/main/twirl/advanced/template.scala.html
  example/src/main/twirl/index.scala.html
  example/src/main/twirl/main.scala.html
  project/BuildHelper.scala
  project/plugins.sbt
Labels: maintenance

#769 Refactor: Remove error type from SocketApp
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/server/ServerSocketHandler.scala
  zio-http/src/main/scala/zhttp/socket/Conversion.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
Labels: enhancement, maintenance, Breaking Change

#772 Refactor: Remove type params from Response
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  example/src/main/scala/example/WebSocketAdvanced.scala
  example/src/main/scala/example/WebSocketEcho.scala
  zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala
  zio-http/src/main/scala/zhttp/http/CanBeSilenced.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/Patch.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/http/Status.scala
  zio-http/src/main/scala/zhttp/http/package.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/main/scala/zhttp/socket/Conversion.scala
  zio-http/src/main/scala/zhttp/socket/IsWebSocket.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/main/scala/zhttp/socket/package.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/middleware/MiddlewareSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: enhancement, maintenance, Breaking Change

#777 Fix: getSetCookieDecoded Method
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
Labels: bug

#779 Feature: Added `updateHeader` to `Patch`
  zio-http/src/main/scala/zhttp/http/Patch.scala
Labels: enhancement

#785 Update sbt-scala3-migrate to 0.5.0
  project/plugins.sbt
Labels: maintenance

#727 Refactor: Add Response Handler
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala
  zio-http/src/main/scala/zhttp/service/server/content/handlers/ServerResponseHandler.scala
Labels: maintenance

#815 Doc: Add outline
  docs/website/docs/client/_category_.json
  docs/website/docs/client/index.md
  docs/website/docs/dsl/_category_.json
  docs/website/docs/dsl/cookies/_category_.json
  docs/website/docs/dsl/cookies/index.md
  docs/website/docs/dsl/headers/_category_.json
  docs/website/docs/dsl/headers/index.md
  docs/website/docs/dsl/http-data/_category_.json
  docs/website/docs/dsl/http-data/index.md
  docs/website/docs/dsl/http-endpoint/_category_.json
  docs/website/docs/dsl/http-endpoint/index.md
  docs/website/docs/dsl/http/_category_.json
  docs/website/docs/dsl/http/index.md
  docs/website/docs/dsl/middleware/_category_.json
  docs/website/docs/dsl/middleware/index.md
  docs/website/docs/dsl/request/_category_.json
  docs/website/docs/dsl/request/index.md
  docs/website/docs/dsl/response/_category_.json
  docs/website/docs/dsl/response/index.md
  docs/website/docs/dsl/server/_category_.json
  docs/website/docs/dsl/server/config.md
  docs/website/docs/dsl/socket/_category_.json
  docs/website/docs/dsl/socket/index.md
  docs/website/docs/examples/_category_.json
  docs/website/docs/examples/advanced-examples/_category_.json
  docs/website/docs/examples/advanced-examples/authentication.md
  docs/website/docs/examples/advanced-examples/concrete-entity.md
  docs/website/docs/examples/advanced-examples/cors.md
  docs/website/docs/examples/advanced-examples/hello-world-advanced.md
  docs/website/docs/examples/advanced-examples/sticky-threads.md
  docs/website/docs/examples/advanced-examples/stream-file.md
  docs/website/docs/examples/advanced-examples/stream-response.md
  docs/website/docs/examples/advanced-examples/web-socket-advanced.md
  docs/website/docs/examples/zio-http-basic-examples/_category_.json
  docs/website/docs/examples/zio-http-basic-examples/hello-world.md
  docs/website/docs/examples/zio-http-basic-examples/https-client.md
  docs/website/docs/examples/zio-http-basic-examples/https-server.md
  docs/website/docs/examples/zio-http-basic-examples/simple-client.md
  docs/website/docs/examples/zio-http-basic-examples/web-socket.md
  docs/website/docs/getting-started.md
  docs/website/docs/index.md
  docs/website/docs/integrations/_category_.json
  docs/website/docs/integrations/index.md
  docs/website/docs/testing/_category_.json
  docs/website/docs/testing/index.md
  docs/website/package-lock.json
Labels: documentation, docs

#811 Update netty-all to 4.1.73.Final
  project/Dependencies.scala
Labels: maintenance

#820 Disable benchmarks comment on fork pull request
  .github/workflows/ci.yml
  project/BenchmarkWorkFlow.scala
Labels: maintenance

#805 Update sbt-scalafix to 0.9.34
  project/plugins.sbt
Labels: bug, maintenance

#814 Docs: Update Basic Examples
  docs/website/docs/examples/zio-http-basic-examples/hello-world.md
  docs/website/docs/examples/zio-http-basic-examples/https-client.md
  docs/website/docs/examples/zio-http-basic-examples/https-server.md
  docs/website/docs/examples/zio-http-basic-examples/simple-client.md
  docs/website/docs/examples/zio-http-basic-examples/web-socket.md
  docs/website/docs/getting-started.md
Labels: docs

#816 Docs: Update advanced examples
  docs/website/docs/examples/advanced-examples/authentication.md
  docs/website/docs/examples/advanced-examples/concrete-entity.md
  docs/website/docs/examples/advanced-examples/cors.md
  docs/website/docs/examples/advanced-examples/hello-world-advanced.md
  docs/website/docs/examples/advanced-examples/sticky-threads.md
  docs/website/docs/examples/advanced-examples/stream-file.md
  docs/website/docs/examples/advanced-examples/stream-response.md
  docs/website/docs/examples/advanced-examples/web-socket-advanced.md
Labels: docs

#832 maintenance: semanticdb revision usage
  project/BuildHelper.scala
Labels: maintenance

#833 Maintenance: workflow scala version
  .github/workflows/ci.yml
  project/BenchmarkWorkFlow.scala
  project/ScoverageWorkFlow.scala
Labels: maintenance

#835 Fix: HasHeader bug
  zio-http/src/main/scala/zhttp/http/headers/HeaderChecks.scala
  zio-http/src/test/scala/zhttp/http/HeaderSpec.scala
Labels: bug

#839 Refactor: update constructor names as per ZIO 2
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpRouteTextPerf.scala
  zio-http-test/src/main/scala/zhttp/test/test.scala
  zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala
  zio-http/src/main/scala/zhttp/http/HExit.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/http/HExitSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: refactor, Breaking Change

#810 Update sbt-bloop to 1.4.12
  project/plugins.sbt
Labels: maintenance

#801 Update scala-library to 2.13.8
  .github/workflows/ci.yml
  project/BuildHelper.scala
  project/ScoverageWorkFlow.scala
Labels: maintenance

#841 Refactor: Middleware Codec
  example/src/main/scala/example/Codec.scala
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/test/scala/zhttp/http/MiddlewareSpec.scala
Labels: middleware

#840 Add Run Before
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/test/scala/zhttp/http/MiddlewareSpec.scala
Labels: middleware

#768 Feature: Add builder methods for `Server`
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: enhancement

#807 Implement missing operators in Middleware
  zio-http/src/main/scala/zhttp/http/Middleware.scala
  zio-http/src/main/scala/zhttp/http/middleware/Cors.scala
  zio-http/src/main/scala/zhttp/http/middleware/Csrf.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/test/scala/zhttp/http/MiddlewareSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
Labels: middleware

#851 Maintenance: html template for internal server error string
  zio-http/src/main/scala/zhttp/core/Util.scala
Labels: maintenance

#856 Refactor: Rename `ClientParams` to `ClientRequest`
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
Labels: Breaking Change

#869 Refactor: use declarative encoding for http.middleware
  zio-http/src/main/scala/zhttp/http/Http.scala
Labels: maintenance

#861 Move docs to v1.x directory
  docs/website/docs/v1.x/_category_.json
  docs/website/docs/v1.x/client/_category_.json
  docs/website/docs/v1.x/client/index.md
  docs/website/docs/v1.x/dsl/_category_.json
  docs/website/docs/v1.x/dsl/cookies/_category_.json
  docs/website/docs/v1.x/dsl/cookies/index.md
  docs/website/docs/v1.x/dsl/headers/_category_.json
  docs/website/docs/v1.x/dsl/headers/index.md
  docs/website/docs/v1.x/dsl/http-data/_category_.json
  docs/website/docs/v1.x/dsl/http-data/index.md
  docs/website/docs/v1.x/dsl/http-endpoint/_category_.json
  docs/website/docs/v1.x/dsl/http-endpoint/index.md
  docs/website/docs/v1.x/dsl/http/_category_.json
  docs/website/docs/v1.x/dsl/http/index.md
  docs/website/docs/v1.x/dsl/middleware/_category_.json
  docs/website/docs/v1.x/dsl/middleware/index.md
  docs/website/docs/v1.x/dsl/request/_category_.json
  docs/website/docs/v1.x/dsl/request/index.md
  docs/website/docs/v1.x/dsl/response/_category_.json
  docs/website/docs/v1.x/dsl/response/index.md
  docs/website/docs/v1.x/dsl/server/_category_.json
  docs/website/docs/v1.x/dsl/server/config.md
  docs/website/docs/v1.x/dsl/socket/_category_.json
  docs/website/docs/v1.x/dsl/socket/index.md
  docs/website/docs/v1.x/examples/_category_.json
  docs/website/docs/v1.x/examples/advanced-examples/_category_.json
  docs/website/docs/v1.x/examples/advanced-examples/authentication.md
  docs/website/docs/v1.x/examples/advanced-examples/concrete-entity.md
  docs/website/docs/v1.x/examples/advanced-examples/cors.md
  docs/website/docs/v1.x/examples/advanced-examples/hello-world-advanced.md
  docs/website/docs/v1.x/examples/advanced-examples/stream-file.md
  docs/website/docs/v1.x/examples/advanced-examples/stream-response.md
  docs/website/docs/v1.x/examples/advanced-examples/web-socket-advanced.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/_category_.json
  docs/website/docs/v1.x/examples/zio-http-basic-examples/hello-world.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/https-client.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/https-server.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/simple-client.md
  docs/website/docs/v1.x/examples/zio-http-basic-examples/web-socket.md
  docs/website/docs/v1.x/getting-started.md
  docs/website/docs/v1.x/index.md
  docs/website/docs/v1.x/integrations/_category_.json
  docs/website/docs/v1.x/integrations/index.md
  docs/website/docs/v1.x/testing/_category_.json
  docs/website/docs/v1.x/testing/index.md
  docs/website/docs/v2.x/_category_.json
  docs/website/docusaurus.config.js
Labels: maintenance, docs

#847 Bug Add host in client from absolute URL
  example/src/main/scala/example/SimpleClient.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: bug, enhancement

#871 Doc: Fix website deployment
  docs/website/docusaurus.config.js
  docs/website/yarn.lock
Labels: bug

#873 Update scala3-library to 3.1.1
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: maintenance

#874 Doc: Fix getting started link
  docs/website/src/pages/index.js
Labels: bug

#864 Update scalafmt-core to 3.3.2
  .scalafmt.conf
Labels: maintenance

#876 Fix collapsible Headers Doc
  docs/website/docs/v1.x/dsl/headers/index.md
  docs/website/yarn.lock
Labels: bug, docs

#852 Test: Added Integration tests for `HExit.Success`
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
Labels: maintenance

#868 Fix: EncodeClientParams
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
Labels: bug

#857 Refactor: HttpRunnableSpec clean up
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/IsResponse.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
Labels: enhancement, maintenance

#897 Fix Documentation
  docs/website/docs/v1.x/getting-started.md
Labels: bug, docs

#887 Docs: Getting started
  docs/website/docs/v1.x/getting-started.md
Labels: docs, ready

#898 refactor: rename `URL.asString` to `encode` in `URI`
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/http/middleware/Web.scala
  zio-http/src/main/scala/zhttp/service/EncodeClientParams.scala
  zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/URLSpec.scala
Labels: maintenance, Breaking Change, ready

#904 refactor: rename asString to encode in Scheme
  zio-http/src/main/scala/zhttp/http/Scheme.scala
  zio-http/src/main/scala/zhttp/http/URL.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
Labels: Breaking Change, ready

#906 Doc: Example links fixed
  docs/website/docs/v1.x/getting-started.md
Labels: bug, docs

#907 Update getting-started.md
  docs/website/docs/v1.x/getting-started.md
Labels: docs

#886 Doc: setup
  docs/website/docs/v1.x/index.md
Labels: docs, ready

#908 Update netty-incubator-transport-native-io_uring to 0.0.12.Final
  project/Dependencies.scala
Labels: ready

#885 Documentation for Server
  docs/website/docs/v1.x/dsl/server/config.md
  docs/website/docs/v1.x/dsl/server/index.md
Labels: docs, ready

#882 Performance: Improve performance server performance when closing connections
  build.sbt
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
Labels: maintenance, performance, ready

#910 Doc: Added <> operator in getting started
  docs/website/docs/v1.x/getting-started.md
Labels: docs, ready

#909 feature: Add `collectManaged` to Http
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/scala/zhttp/http/HttpSpec.scala
Labels: enhancement, ready

#900 Feature: add `echo` operator to `Socket`
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: enhancement, ready

#901 feature: add `Socket.empty`
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: enhancement, ready

#902 feature: add `toHttp` to Socket.scala
  zio-http/src/main/scala/zhttp/socket/Socket.scala
  zio-http/src/test/scala/zhttp/socket/SocketSpec.scala
Labels: enhancement, ready

#903 Feature: add `toHttp` to Response
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
Labels: enhancement, ready
