Repository zio/zio-http, pull requests merged in 2022-08, with the labels that each got.

#1351 Refactor: Re-write `HttpData` to `Body`
  docs/website/docs/v1.x/dsl/body.md
  docs/website/docs/v1.x/dsl/headers.md
  docs/website/docs/v1.x/dsl/httpdata.md
  docs/website/docs/v1.x/dsl/request.md
  docs/website/docs/v1.x/dsl/response.md
  docs/website/docs/v1.x/examples/advanced-examples/stream-response.md
  example/src/main/scala/example/AuthenticationClient.scala
  example/src/main/scala/example/HttpsClient.scala
  example/src/main/scala/example/PlainTextBenchmarkServer.scala
  example/src/main/scala/example/RequestStreaming.scala
  example/src/main/scala/example/SimpleClient.scala
  example/src/main/scala/example/StreamingResponse.scala
  zio-http/src/main/scala/zhttp/http/Body.scala
  zio-http/src/main/scala/zhttp/http/HExit.scala
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/main/scala/zhttp/http/HttpData.scala
  zio-http/src/main/scala/zhttp/http/HttpDataExtension.scala
  zio-http/src/main/scala/zhttp/http/HttpError.scala
  zio-http/src/main/scala/zhttp/http/Request.scala
  zio-http/src/main/scala/zhttp/http/Response.scala
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/ContentHandler.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/main/scala/zhttp/service/EventLoopGroup.scala
  zio-http/src/main/scala/zhttp/service/FastPassWriter.scala
  zio-http/src/main/scala/zhttp/service/FullPassWriter.scala
  zio-http/src/main/scala/zhttp/service/Handler.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
  zio-http/src/main/scala/zhttp/service/RequestBodyHandler.scala
  zio-http/src/main/scala/zhttp/service/Server.scala
  zio-http/src/main/scala/zhttp/service/ServerResponseWriter.scala
  zio-http/src/main/scala/zhttp/service/WebSocketAppHandler.scala
  zio-http/src/main/scala/zhttp/service/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zhttp/service/package.scala
  zio-http/src/main/scala/zhttp/service/server/ServerChannelFactory.scala
  zio-http/src/main/scala/zhttp/service/server/ServerTime.scala
  zio-http/src/main/scala/zhttp/service/server/WebSocketUpgrade.scala
  zio-http/src/test/resources/TestFile.txt
  zio-http/src/test/scala/zhttp/http/BodySpec.scala
  zio-http/src/test/scala/zhttp/http/EncodeRequestSpec.scala
  zio-http/src/test/scala/zhttp/http/GetBodyAsStringSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpDataSpec.scala
  zio-http/src/test/scala/zhttp/http/HttpErrorSpec.scala
  zio-http/src/test/scala/zhttp/http/ResponseSpec.scala
  zio-http/src/test/scala/zhttp/http/middleware/WebSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
  zio-http/src/test/scala/zhttp/internal/HttpRunnableSpec.scala
  zio-http/src/test/scala/zhttp/service/ClientSpec.scala
  zio-http/src/test/scala/zhttp/service/RequestStreamingServerSpec.scala
  zio-http/src/test/scala/zhttp/service/SSLSpec.scala
  zio-http/src/test/scala/zhttp/service/ServerSpec.scala
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
Labels: enhancement, maintenance, refactor, docs, Breaking Change

#1367 Refactor: Use builder pattern for SocketDecoder and SocketProtocol
  example/src/main/scala/example/WebSocketAdvanced.scala
  zio-http/src/main/scala/zhttp/socket/SocketApp.scala
  zio-http/src/main/scala/zhttp/socket/SocketDecoder.scala
  zio-http/src/main/scala/zhttp/socket/SocketProtocol.scala
Labels: maintenance, Breaking Change

#1392 Update scalafmt-core to 3.5.9
  .scalafmt.conf
Labels: maintenance

#1388 Chore: add dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: maintenance

#1299 Update scala-library, scala-reflect to 2.12.16
  .github/workflows/ci.yml
  project/BuildHelper.scala
Labels: maintenance

#1398 Change to code snippet compatible with ZIO 2
  README.md
Labels: docs

#1393 Feature: Add the ability to get resources from JAR archives
  zio-http/src/main/scala/zhttp/http/Http.scala
  zio-http/src/test/resources/TestArchive.jar
  zio-http/src/test/scala/zhttp/service/StaticFileServerSpec.scala
Labels: enhancement

#1406 Update ZIO Version
  project/Dependencies.scala
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/HttpRouteTextPerf.scala
  zio-http/src/main/scala/zhttp/service/HttpRuntime.scala
Labels: automerge

#1373 Fix: Host header must include port
  zio-http/src/main/scala/zhttp/service/Client.scala
  zio-http/src/main/scala/zhttp/service/EncodeRequest.scala
  zio-http/src/test/scala/zhttp/http/EncodeRequestSpec.scala
Labels: bug

#1385 Fix: Validate cookie signature on request
  zio-http/src/main/scala/zhttp/http/Cookie.scala
  zio-http/src/main/scala/zhttp/http/headers/HeaderGetters.scala
  zio-http/src/test/scala/zhttp/http/CookieSpec.scala
  zio-http/src/test/scala/zhttp/internal/HttpGen.scala
Labels: bug
