Repository zio/zio-http, pull requests merged in 2024-01, with the labels that each got.

#2563 Content-Length, chunked transfer encoding and Host header improvements
  docs/dsl/body.md
  docs/dsl/headers.md
  docs/examples/advanced/streaming-file.md
  docs/examples/advanced/streaming-response.md
  zio-http-cli/src/main/scala/zio/http/endpoint/cli/Retriever.scala
  zio-http-example/src/main/scala/example/FileStreaming.scala
  zio-http-example/src/main/scala/example/RequestStreaming.scala
  zio-http-example/src/main/scala/example/StreamingResponse.scala
  zio-http/src/main/scala/zio/http/Body.scala
  zio-http/src/main/scala/zio/http/Handler.scala
  zio-http/src/main/scala/zio/http/Response.scala
  zio-http/src/main/scala/zio/http/codec/internal/BodyCodec.scala
  zio-http/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
  zio-http/src/main/scala/zio/http/netty/NettyBody.scala
  zio-http/src/main/scala/zio/http/netty/NettyBodyWriter.scala
  zio-http/src/main/scala/zio/http/netty/NettyResponse.scala
  zio-http/src/main/scala/zio/http/netty/NettyResponseEncoder.scala
  zio-http/src/main/scala/zio/http/netty/client/NettyRequestEncoder.scala
  zio-http/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
  zio-http/src/test/scala/zio/http/BodySpec.scala
  zio-http/src/test/scala/zio/http/ClientSpec.scala
  zio-http/src/test/scala/zio/http/ClientStreamingSpec.scala
  zio-http/src/test/scala/zio/http/HandlerSpec.scala
  zio-http/src/test/scala/zio/http/ResponseCompressionSpec.scala
  zio-http/src/test/scala/zio/http/ServerSpec.scala
  zio-http/src/test/scala/zio/http/internal/HttpGen.scala
  zio-http/src/test/scala/zio/http/netty/NettyBodySpec.scala
  zio-http/src/test/scala/zio/http/netty/NettyStreamBodySpec.scala
  zio-http/src/test/scala/zio/http/netty/client/NettyConnectionPoolSpec.scala
Labels: docs

#2597 Optimize RichTextCodec
  zio-http-benchmarks/src/main/scala/zhttp.benchmarks/ProbeContentTypeBenchmark.scala
  zio-http/src/main/scala/zio/http/Header.scala
  zio-http/src/main/scala/zio/http/codec/RichTextCodec.scala
  zio-http/src/test/scala/zio/http/codec/RichTextCodecSpec.scala
Labels: 🙋 Bounty claim

#2595 Add missing default http headers (#2557)
  zio-http-gen/src/main/scala/zio/http/gen/scala/CodeGen.scala
  zio-http/src/main/scala/zio/http/Header.scala
  zio-http/src/main/scala/zio/http/codec/HeaderCodecs.scala
  zio-http/src/test/scala/zio/http/headers/ClearSiteDataSpec.scala
  zio-http/src/test/scala/zio/http/headers/ForwardedSpec.scala
  zio-http/src/test/scala/zio/http/headers/LinkSpec.scala
  zio-http/src/test/scala/zio/http/internal/HttpGen.scala
Labels: 🙋 Bounty claim

#2593 Use `zio.Config.Secret` instead of `String` to avoid leaks (#2508)
  zio-http/src/main/scala/zio/http/ClientSSLConfig.scala
  zio-http/src/main/scala/zio/http/Credentials.scala
  zio-http/src/main/scala/zio/http/HandlerAspect.scala
  zio-http/src/main/scala/zio/http/Header.scala
  zio-http/src/main/scala/zio/http/Proxy.scala
  zio-http/src/main/scala/zio/http/netty/NettyProxy.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientSSLConverter.scala
  zio-http/src/test/scala/zio/http/ClientProxySpec.scala
  zio-http/src/test/scala/zio/http/internal/middlewares/AuthSpec.scala
  zio-http/src/test/scala/zio/http/netty/NettyProxySpec.scala
Labels: 🙋 Bounty claim

#2596 Handle defects in handled routes (#2580)
  zio-http/src/main/scala/zio/http/Route.scala
  zio-http/src/test/scala/zio/http/RouteSpec.scala
Labels: 🙋 Bounty claim

#2599 Fix hanging on stream response errors
  zio-http/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
  zio-http/src/test/scala/zio/http/ServerSpec.scala
Labels: 🙋 Bounty claim

#2600 Only Handlers with Request input can have HandlerAspects applied (#2527)
  zio-http/src/main/scala/zio/http/Handler.scala
Labels: 🙋 Bounty claim

#2601 Update testkit to use common DSL (#2559)
  zio-http-cli/src/test/scala/zio/http/endpoint/cli/CliSpec.scala
  zio-http-testkit/src/main/scala/zio/http/TestClient.scala
  zio-http-testkit/src/main/scala/zio/http/TestServer.scala
  zio-http-testkit/src/test/scala/zio/http/TestClientSpec.scala
  zio-http-testkit/src/test/scala/zio/http/TestServerSpec.scala
  zio-http/src/main/scala/zio/http/HttpApp.scala
Labels: 🙋 Bounty claim

#2591 Implement QueryParam ordering
  zio-http/src/main/scala/zio/http/Form.scala
  zio-http/src/main/scala/zio/http/QueryParams.scala
  zio-http/src/main/scala/zio/http/URL.scala
  zio-http/src/main/scala/zio/http/netty/NettyQueryParamEncoding.scala
  zio-http/src/test/scala/zio/http/QueryParamsSpec.scala
  zio-http/src/test/scala/zio/http/URLSpec.scala
Labels: 🙋 Bounty claim

#2589 feat: htmx attributes
  .github/workflows/ci.yml
  build.sbt
  zio-http-htmx/src/main/scala/zio/http/htmx/Attributes.scala
Labels: 🙋 Bounty claim

#2468 Reproducer and fix for multipart/form-data bug
  zio-http/src/main/scala/zio/http/StreamingForm.scala
  zio-http/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
  zio-http/src/test/scala/zio/http/endpoint/RoundtripSpec.scala
Labels: bug, 🙋 Bounty claim

#2610 Fix Client hanging on unexpected Channel closures
  zio-http/src/main/scala/zio/http/ZClient.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientInboundHandler.scala
  zio-http/src/main/scala/zio/http/netty/client/ClientResponseStreamHandler.scala
  zio-http/src/main/scala/zio/http/netty/client/NettyClientDriver.scala
  zio-http/src/main/scala/zio/http/netty/client/NettyConnectionPool.scala
  zio-http/src/test/scala/zio/http/ClientHttpsSpec.scala
  zio-http/src/test/scala/zio/http/SSLSpec.scala
  zio-http/src/test/scala/zio/http/ServerSpec.scala
  zio-http/src/test/scala/zio/http/netty/client/NettyConnectionPoolSpec.scala
Labels: 🙋 Bounty claim

#2619 Fixed #2373: don't propagate ReadTimeoutExceptions
  zio-http/src/main/scala/zio/http/netty/client/NettyConnectionPool.scala
  zio-http/src/main/scala/zio/http/netty/package.scala
Labels: 🙋 Bounty claim

#2636 Fallback to smaller priority Accept headers
  zio-http/jvm/src/test/scala/zio/http/endpoint/RequestSpec.scala
  zio-http/shared/src/main/scala/zio/http/codec/HttpCodec.scala
  zio-http/shared/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
Labels: 🙋 Bounty claim

#2618 chore: update project plugins
  .github/workflows/site.yml
  README.md
  build.sbt
  project/plugins.sbt
Labels: 🙋 Bounty claim

#2634 Fix #2622: don't remove 'val' from case classes' parameters with names containing 'val' in them
  zio-http-gen/src/main/scala/zio/http/gen/scala/CodeGen.scala
  zio-http-gen/src/test/resources/GeneratedValues.scala
  zio-http-gen/src/test/scala/zio/http/gen/model/Values.scala
  zio-http-gen/src/test/scala/zio/http/gen/scala/CodeGenSpec.scala
Labels: 🙋 Bounty claim

#2635 Fix OpenAPI example extraction
  zio-http-cli/src/main/scala/zio/http/endpoint/cli/CliEndpoint.scala
  zio-http-cli/src/main/scala/zio/http/endpoint/cli/HttpOptions.scala
  zio-http-cli/src/test/scala/zio/http/endpoint/cli/CommandGen.scala
  zio-http/jvm/src/test/resources/endpoint/openapi/multiple-methods-on-same-path.json
  zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala
  zio-http/shared/src/main/scala/zio/http/codec/HttpCodec.scala
  zio-http/shared/src/main/scala/zio/http/codec/PathCodec.scala
  zio-http/shared/src/main/scala/zio/http/codec/SegmentCodec.scala
  zio-http/shared/src/main/scala/zio/http/codec/internal/AtomizedCodecs.scala
  zio-http/shared/src/main/scala/zio/http/codec/internal/Mechanic.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/OpenAPI.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/OpenAPIGen.scala
Labels: 🙋 Bounty claim

#2643 OpenAPI code gen collections fix (#2620)
  zio-http-gen/src/main/scala/zio/http/gen/openapi/EndpointGen.scala
  zio-http-gen/src/main/scala/zio/http/gen/scala/CodeGen.scala
  zio-http-gen/src/test/resources/GeneratedUserNameArray.scala
  zio-http-gen/src/test/scala/zio/http/gen/model/User.scala
  zio-http-gen/src/test/scala/zio/http/gen/model/UserNameArray.scala
  zio-http-gen/src/test/scala/zio/http/gen/openapi/EndpointGenSpec.scala
  zio-http-gen/src/test/scala/zio/http/gen/scala/CodeGenSpec.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/OpenAPIGen.scala
Labels: 🙋 Bounty claim

#2631 Intoroduce query parameters with multiple values to Endpoint API
  zio-http-cli/src/main/scala/zio/http/endpoint/cli/CliEndpoint.scala
  zio-http-cli/src/test/scala/zio/http/endpoint/cli/EndpointGen.scala
  zio-http/jvm/src/test/scala/zio/http/endpoint/EndpointSpec.scala
  zio-http/jvm/src/test/scala/zio/http/endpoint/QueryParameterSpec.scala
  zio-http/shared/src/main/scala/zio/http/codec/HttpCodec.scala
  zio-http/shared/src/main/scala/zio/http/codec/QueryCodecs.scala
  zio-http/shared/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/OpenAPIGen.scala
Labels: 🙋 Bounty claim

#2657 Try to read oneOf, before handling empty schema type as Object (#2623)
  zio-http-gen/src/main/scala/zio/http/gen/openapi/EndpointGen.scala
  zio-http-gen/src/test/scala/zio/http/gen/openapi/EndpointGenSpec.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala
Labels: 🙋 Bounty claim

#2656 Update Examples
  build.sbt
  docs/examples/advanced/authentication.md
  docs/examples/advanced/concrete-entity.md
  docs/examples/advanced/middleware-basic-authentication.md
  docs/examples/advanced/middleware-cors-handling.md
  docs/examples/advanced/server.md
  docs/examples/advanced/static-files.md
  docs/examples/advanced/streaming-file.md
  docs/examples/advanced/streaming-response.md
  docs/examples/advanced/websocket.md
  docs/examples/authentication.md
  docs/examples/basic/http-client.md
  docs/examples/basic/http-server.md
  docs/examples/basic/https-client.md
  docs/examples/basic/https-server.md
  docs/examples/basic/websocket.md
  docs/examples/cli.md
  docs/examples/concrete-entity.md
  docs/examples/cookie.md
  docs/examples/endpoint.md
  docs/examples/graceful-shutdown.md
  docs/examples/hello-world.md
  docs/examples/html-templating.md
  docs/examples/http-client-server.md
  docs/examples/https-client-server.md
  docs/examples/middleware-cors-handling.md
  docs/examples/multipart-form-data.md
  docs/examples/server-sent-events-in-endpoints.md
  docs/examples/serving-static-files.md
  docs/examples/static-files.md
  docs/examples/streaming.md
  docs/examples/websocket.md
  docs/sidebars.js
  zio-http-docs/src/main/scala/utils.scala
  zio-http-example/src/main/scala/example/HttpsHelloWorld.scala
Labels: documentation
