Repository zio/zio-http, pull requests merged in 2024-07, with the labels that each got.

#2949 Use ZIO Assistant to Update Readme
  .github/workflows/site.yml
Labels: maintenance

#2959 Multi-value segments for PathCodecs
  zio-http-cli/src/main/scala/zio/http/endpoint/cli/HttpOptions.scala
  zio-http-cli/src/test/scala/zio/http/endpoint/cli/CommandGen.scala
  zio-http/jvm/src/test/scala/zio/http/codec/PathCodecSpec.scala
  zio-http/shared/src/main/scala/zio/http/codec/PathCodec.scala
  zio-http/shared/src/main/scala/zio/http/codec/SegmentCodec.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala
  zio-http/shared/src/main/scala/zio/http/endpoint/openapi/OpenAPIGen.scala
  zio-http/shared/src/main/scala/zio/http/package.scala
  zio-http/shared/src/test/scala/zio/http/codec/SegmentCodecSpec.scala
Labels: 🙋 Bounty claim

#2951 Encode SSE based on HttpContentCodec (#2695)
  zio-http/shared/src/main/scala/zio/http/ServerSentEvent.scala
  zio-http/shared/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
Labels: 🙋 Bounty claim

#2989 Fix doc typo
  docs/guides/testing-http-apps.md
Labels: bug, docs

#2986 Allow nesting `Routes` with unhandled errors (#2934)
  zio-http/jvm/src/test/scala/zio/http/RoutesSpec.scala
  zio-http/shared/src/main/scala/zio/http/Route.scala
  zio-http/shared/src/main/scala/zio/http/Routes.scala
  zio-http/shared/src/main/scala/zio/http/codec/PathCodec.scala
Labels: 🙋 Bounty claim

#2983 Handle content new lines in `fromFormAST` (#2976)
  zio-http/jvm/src/test/scala/zio/http/FormSpec.scala
  zio-http/shared/src/main/scala/zio/http/FormField.scala
Labels: 🙋 Bounty claim

#2990 Remove deprecated App (#2984)
  zio-http/shared/src/main/scala/zio/http/Handler.scala
  zio-http/shared/src/main/scala/zio/http/HttpApp.scala
  zio-http/shared/src/main/scala/zio/http/Route.scala
  zio-http/shared/src/main/scala/zio/http/Routes.scala
  zio-http/shared/src/main/scala/zio/http/Server.scala
  zio-http/shared/src/main/scala/zio/http/WebSocketApp.scala
Labels: 🙋 Bounty claim
